# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef3ec891066cdbcff86f83f28a36fdae184d2560834c38c243d94ef637237f1b33703174ec0a0ada50c12f1e5eae73fddff24ea5580b0bdd511753f792f9e789

test:
  secret_key_base: d72305c87049ba0dc1e197625f9f99e9d1f6e0199af0455d6d67fbfc09e694ee9755448fc2fdf6eefc40f91d1980197c27966dd96a4e639bb92f1ccd77127167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
